# Generated by Django 4.2.8 on 2024-05-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='은행 이름')),
                ('bank_tag', models.CharField(max_length=20, verbose_name='은행 종류')),
                ('bank_image', models.ImageField(upload_to='bank_images/', verbose_name='은행 이미지')),
                ('bank_url', models.URLField(blank=True, null=True, verbose_name='은행 URL')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='적금 이름')),
                ('updated_at', models.CharField(max_length=20, verbose_name='업데이트 일시')),
                ('join_member', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 회원')),
                ('join_deny', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 거부')),
                ('join_way', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 방법')),
                ('save_trm', models.IntegerField(verbose_name='저축 기간')),
                ('max_limit', models.IntegerField(blank=True, null=True, verbose_name='최대 한도')),
                ('intr_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='이율')),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='이율2')),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='금리 유형')),
                ('spcl_cnd', models.CharField(blank=True, max_length=255, null=True, verbose_name='특별 조건')),
                ('etc_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 노트')),
                ('pin_number', models.CharField(max_length=255, verbose_name='핀 넘버')),
                ('bank_code', models.CharField(max_length=255, verbose_name='금융회사 코드')),
                ('isCheck', models.BooleanField(verbose_name='이전 자료 비교 여부 확인')),
                ('rsrv_type', models.CharField(max_length=20, verbose_name='적립 유형')),
                ('views', models.IntegerField(default=0, verbose_name='조회순')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankDatas.bank', verbose_name='은행')),
                ('liked_by_users', models.ManyToManyField(related_name='liked_savings_accounts', to=settings.AUTH_USER_MODEL, verbose_name='찜한 유저들')),
            ],
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='정기예금 이름')),
                ('updated_at', models.CharField(max_length=20, verbose_name='업데이트 일시')),
                ('join_member', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 회원')),
                ('join_deny', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 거부')),
                ('join_way', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 방법')),
                ('save_trm', models.IntegerField(verbose_name='저축 기간')),
                ('max_limit', models.IntegerField(blank=True, null=True, verbose_name='최대 한도')),
                ('intr_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='이율')),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='이율2')),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='금리 유형')),
                ('spcl_cnd', models.CharField(blank=True, max_length=255, null=True, verbose_name='특별 조건')),
                ('etc_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='기타 노트')),
                ('pin_number', models.CharField(max_length=255, verbose_name='핀 넘버')),
                ('bank_code', models.CharField(max_length=255, verbose_name='금융회사 코드')),
                ('isCheck', models.BooleanField(verbose_name='이전 자료 비교 여부 확인')),
                ('views', models.IntegerField(default=0, verbose_name='조회순')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankDatas.bank', verbose_name='은행')),
                ('liked_by_users', models.ManyToManyField(related_name='liked_fixed_accounts', to=settings.AUTH_USER_MODEL, verbose_name='찜한 유저들')),
            ],
        ),
    ]
