# Generated by Django 4.2.8 on 2024-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회순'),
        ),
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회순'),
        ),
    ]
